# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import pybb.util


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0007_auto_20170111_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=pybb.util.FilePathGenerator(to='pybb_upload\\attachments'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='autosubscribe',
            field=models.BooleanField(default=False, help_text='Automatically subscribe to topics that you answer', verbose_name='Automatically subscribe'),
        ),
    ]
