# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0009_auto_20171017_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybb.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_signatures',
            field=models.BooleanField(default=True, verbose_name='Показывать подпись'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Подпись на форуме'),
        ),
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybb.Profile'),
        ),
    ]
