# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0011_auto_20190415_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
